spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/data_bus?useSSL=false
    username: root
    password: 2001
  flyway:
      baseline-on-migrate: true
  main:
      allow-circular-references: true